backend:
  name: github
  repo: WohenYoumo/Mizuki
  branch: master
  base_url: https://mizuki-cms-auth.whym114.workers.dev
  auth_endpoint: /auth
  token_endpoint: /token

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "post"
    label: "文章"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "发布日期", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss", default: "" }
      - { label: "封面图", name: "cover", widget: "image", required: false }
      - { label: "正文", name: "body", widget: "markdown" }
